# Generated by Django 4.2.6 on 2023-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planetarium",
            "0002_alter_planetariumdome_name_alter_showtheme_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
