# Generated by Django 4.2.6 on 2023-10-20 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_astronomyshow_show_theme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
    ]
