# Generated by Django 4.2.6 on 2023-10-20 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0006_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "show_session")},
        ),
    ]
