# Generated by Django 4.2.6 on 2023-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0008_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetariumdome",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="???"),
        ),
    ]
