# Generated by Django 4.2.6 on 2023-10-23 11:19

from django.db import migrations, models
import planetarium.models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0009_planetariumdome_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetariumdome",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium.models.planetarium_dome_image_path,
            ),
        ),
    ]
